# Change these first
owner: xcash-rocks # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: xcash.rocks
    url: http://node.xcash.rocks
  - name: lowfee.xcash.rocks
    url: http://lowfee.xcash.rocks
  - name: pi.xcash.rocks
    url: http://pi.xcash.rocks
  - name: crazy.xcash.rocks
    url: http://crazy.xcash.rocks

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://xcash.rocks/xcash-rocket-toTop.svg
  name: xcash.rocks nodes
  introTitle: "Welcome to xcash.rocks uptime monitor!"
  introMessage:
  navbar:
    - title: Node Status
      href: https://xcash-rocks.github.io/upptime/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
